# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                  boris:
                      password: $2y$12$72sBN5uRl/gnJhlVs7O6lu/y3gZ4dM52wYTuru3DNvzauX4NT32Pe
                      roles: 'ROLE_USER'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/tickets/submit, roles: ROLE_USER }
